### ISSUE TITLE
Relation between motion vectors and optical flow

### ISSUE THREAD

**Issue by lu-m13** [keijiro/KinoVision#3]
Hi, 

Thanks for your project.

I want to convert motion vectors to optical flow in pixel.

Could please give me some advice on the relation between them.

Thanks a lot.

**Comment by keijiro** [comment]
Usually, optical flows are used to imitate motion vectors.

So, I think "convert motion vectors to optical flow" doesn't make sense.

It sounds like converting breads into flour. I can't understand why it's needed.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by lu-m13** [comment]
Hi, Thanks for replying me. 

I am working on building a dataset with ground-truth optical flows (similar to Sintel - http://sintel.is.tue.mpg.de/). 

I use the following project: https://bitbucket.org/Unity-Technologies/ml-imagesynthesis/src/master/

However, it can only export the colored images of motion vectors. I can not find a clear explanation about motion vectors. So,

What is the range of motion vectors?  (someone says it is [-1,1] for in screen pixels)  

Can I convert it to pixel by (motion vector).x * width/2 and (motion vector).y * height/2 ?

Does motion vector calculate the difference between current frame and last frame (backward flow)?  or between current frame and next frame (forward flow)?

Thanks a lot.

**Comment by keijiro** [comment]
Thanks for the clarification. It makes sense.

Motion vectors are calculated like the following.

https://github.com/keijiro/DrawMeshWithMotionVectors/blob/master/Assets/MotionVectors.shader#L33

So, the R and G components of each pixel contain difference between the last frame and the current frame. Values are calculated in the screen space (0,0)-(1,1).

**Comment by lu-m13** [comment]
It seems work now. 

Thanks very much!
